integration/config/routes.rb
Integration::Application.routes.draw do

  root :to => 'autocomplete#new'
  match 'autocomplete/autocomplete_brand_name' => 'autocomplete#autocomplete_brand_name'

  resources :products
  resources :id_elements do
    get :autocomplete_brand_name, :on => :collection
  end

  resources :sub_classes do
    get :autocomplete_foreign_brand_name, :on => :collection
  end

  resources :multiple_selections do
    get :autocomplete_brand_name, :on => :collection
  end

  resources :nested_models do
    get :autocomplete_feature_name, :on => :collection
  end

  resources :simple_forms do
    get :autocomplete_feature_name, :on => :collection
  end
end

integration/app/models/brand.rb
class Brand < ActiveRecord::Base
end

integration/app/models/feature.rb
class Feature < ActiveRecord::Base
end

integration/app/models/foreign_brand.rb
class ForeignBrand < Brand

end

integration/app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessor :brand_id

  has_many :features
  accepts_nested_attributes_for :features
end

integration/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

integration/app/controllers/autocomplete_controller.rb
class AutocompleteController < ApplicationController
  autocomplete :brand, :name

  def new
    @product = Product.new
  end
end

integration/app/controllers/id_elements_controller.rb
class IdElementsController < ApplicationController
  autocomplete :brand, :name

  def new
    @product = Product.new
  end

end

integration/app/controllers/multiple_selections_controller.rb
class MultipleSelectionsController < ApplicationController
  autocomplete :brand, :name

  def new
    @product = Product.new
  end
end

integration/app/controllers/nested_models_controller.rb
class NestedModelsController < ApplicationController
  autocomplete :feature, :name

  def new
    @product = Product.new
    @feature = @product.features.build(:name => 'Glowy,')
  end
end

integration/app/controllers/simple_forms_controller.rb
class SimpleFormsController < ApplicationController
  autocomplete :brand, :name

  def new
    @product = Product.new
  end
end

integration/app/controllers/sub_classes_controller.rb
class SubClassesController < ApplicationController
  autocomplete :foreign_brand, :name

  def new
    @product = Product.new
  end
end

integration/app/helpers/application_helper.rb
module ApplicationHelper
end

integration/app/helpers/autocomplete_helper.rb
module AutocompleteHelper
end

integration/app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= "Invalid Fields"
    options[:message] ||= "Correct the following errors and try again."
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

integration/app/helpers/id_elements_helper.rb
module IdElementsHelper
end

integration/app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

integration/app/helpers/sub_classes_helper.rb
module SubClassesHelper
end

integration/app/views/autocomplete/new.html.haml
%h1 Autocomplete

= form_for @product do |form|
  %p
    = form.label :name
    = form.text_field :name
  %p
    = form.label :brand_name
    = form.autocomplete_field :brand_name, autocomplete_autocomplete_brand_name_path

integration/app/views/id_elements/new.html.haml
%h1 Id Element

= form_for @product do |form|
  %p
    = form.label :name
    = form.text_field :name
  %p
    = form.label :brand_name
    = form.autocomplete_field :brand_name, autocomplete_brand_name_id_elements_path, :id_element => '#product_brand_id'
  %p
    = form.label :brand_id
    = form.text_field :brand_id

integration/app/views/layouts/application.html.haml
!!!
%html

  %head
    %title
      = yield(:title) || "Untitled"
    %meta{"http-equiv"=>"Content-Type", :content=>"text/html; charset=utf-8"}/
    = stylesheet_link_tag "application", 'jquery-ui-1.8.2.custom'
    = javascript_include_tag 'jquery-1.5.1.min.js', 'jquery-ui.min.js', 'rails', 'autocomplete-rails'
    = csrf_meta_tag
    = yield(:head)

  %body
    #container
      - flash.each do |name, msg|
        = content_tag :div, msg, :id => "flash_#{name}"

      - if show_title?
        %h1= yield(:title)

      = yield

integration/app/views/multiple_selections/new.html.haml
%h1 Multiple

= form_for @product do |form|
  %p
    = form.label :name
    = form.text_field :name
  %p
    = form.label :brand_name
    = form.autocomplete_field :brand_name, autocomplete_brand_name_multiple_selections_path, :"data-delimiter" => ','

integration/app/views/nested_models/new.html.haml
%h1 Nested Models example
= form_for @product do |form|
  %p
    = form.label :name
    = form.text_field :name
  %p
    = form.fields_for :features do |feature_form|
      = feature_form.label :name, "Feature Name"
      = feature_form.autocomplete_field :name, autocomplete_feature_name_nested_models_path, :"data-delimiter" => ','
      = feature_form.text_field :name

integration/app/views/simple_forms/new.html.haml
%h1 Autocomplete

= simple_form_for @product do |form|
  %p
    = form.input :name
  %p
    = form.input :brand_name, :url => autocomplete_autocomplete_brand_name_path, :as => :autocomplete

integration/app/views/sub_classes/new.html.haml
%h1 Subclasses

= form_for @product do |form|
  %p
    = form.label :name
    = form.text_field :name
  %p
    = form.label :brand_name
    = form.autocomplete_field :brand_name, autocomplete_foreign_brand_name_sub_classes_path